# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WBBpUsq5K-8kEeBVbUKVE60Awa6_LDU
"""

import streamlit as st
from backend import predict_demand, inventory_optimization

st.title("📦 Demand Forecasting & Inventory Optimization")


# SECTION 1: Demand Forecast

st.header("📈 Demand Forecasting")

product_id = st.text_input("Enter Product ID")
selected_date = st.date_input("Select Date")

if st.button("Predict Demand"):
    forecast = predict_demand(product_id)

    if selected_date in forecast.index:
        st.success(f"Predicted Demand: {forecast[selected_date]}")
    else:
        st.warning("Date not in forecast range")

    st.line_chart(forecast)


# SECTION 2: Inventory

st.header("📦 Inventory Optimization")

inv_product_id = st.text_input("Enter Product ID for Inventory")

if st.button("Optimize Inventory"):
    forecast = predict_demand(inv_product_id)

    result = inventory_optimization(forecast)

    st.write("### Results")
    st.write(f"Optimal Order Quantity: {result['order_quantity']}")
    st.write(f"Reorder Point: {result['reorder_point']}")
    st.write(f"Safety Stock: {result['safety_stock']}")
    st.write(f"Total Cost: {result['total_cost']}")
