# -*- coding: utf-8 -*-
"""reusable prediction functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4gpHJhUahK126eiaFPwP7iu8jNbxlmi
"""

import joblib
import pandas as pd
import numpy as np


import pandas as pd

data = pd.read_csv("demand_inventory.csv")
data['Date'] = pd.to_datetime(data['Date'])
time_series = data.set_index('Date')['Demand']

# Load model
model = joblib.load("demand_forecasting_model.pkl")

def predict_demand(product_id, steps=10):
    product_data = data[data['Product_ID'] == product_id]
    ts = product_data.set_index('Date')['Demand']

    predictions = model.predict(start=len(ts), end=len(ts)+steps-1)
    return predictions.astype(int)

    future_dates = pd.date_range(
        start=time_series.index[-1] + pd.DateOffset(days=1),
        periods=steps,
        freq='D'
    )

    forecast = pd.Series(predictions, index=future_dates)
    return forecast


def inventory_optimization(forecasted_demand):
    initial_inventory = 5500
    lead_time = 1
    service_level = 0.95

    z = np.abs(np.percentile(forecasted_demand, 100 * (1 - service_level)))

    order_quantity = int(np.ceil(forecasted_demand.mean() + z))
    reorder_point = forecasted_demand.mean() * lead_time + z
    safety_stock = reorder_point - forecasted_demand.mean() * lead_time

    holding_cost = 0.1
    stockout_cost = 10

    total_holding_cost = holding_cost * (initial_inventory + 0.5 * order_quantity)
    total_stockout_cost = stockout_cost * max(0, forecasted_demand.mean() * lead_time - initial_inventory)

    total_cost = total_holding_cost + total_stockout_cost

    return {
        "order_quantity": order_quantity,
        "reorder_point": reorder_point,
        "safety_stock": safety_stock,
        "total_cost": total_cost
    }
